{% set version = "2.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rversions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rversions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rversions/rversions_{{ version }}.tar.gz
  sha256: 51ec1f64e7d628e88d716a020d5d521eba71d472e3c9ae7b694428ef6dd786c5

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-curl
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-curl
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('rversions')"           # [not win]
    - "\"%R%\" -e \"library('rversions')\""  # [win]

about:
  home: https://github.com/r-hub/rversions, https://r-hub.github.io/rversions
  license: MIT
  license_file: LICENSE
  summary: Query the main 'R' 'SVN' repository to find the versions 'r-release' and 'r-oldrel'
    refer to, and also all previous 'R' versions and their release dates.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rversions
# Title: Query 'R' Versions, Including 'r-release' and 'r-oldrel'
# Version: 1.1.0
# Authors@R: c( person("Gabor", "Csardi", , "csardi.gabor@gmail.com", role = c("aut", "cre")), person("Jeroen", "Ooms", , "jeroen.ooms@stat.ucla.edu", role = "ctb"), person("R Consortium", role = c("fnd")))
# Description: Query the main 'R' 'SVN' repository to find the versions 'r-release' and 'r-oldrel' refer to, and also all previous 'R' versions and their release dates.
# License: MIT + file LICENSE
# URL: https://github.com/r-hub/rversions, https://r-hub.github.io/rversions
# BugReports: https://github.com/r-hub/rversions/issues
# Imports: curl, xml2 (>= 1.0.0), utils
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Suggests: mockery, testthat
# NeedsCompilation: no
# Packaged: 2019-04-11 10:28:28 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Jeroen Ooms [ctb], R Consortium [fnd]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-11 10:42:43 UTC
