{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rversions
  version: {{ version|replace("-", "_") }}

source:
  fn: rversions_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rversions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rversions/rversions_{{ version }}.tar.gz
  sha256: 14a5a2f06b74e332fd9cbd4d715baa6165f5269c9ba2c0b9f1d0c6540dde9c3c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-curl
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-curl
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('rversions')"           # [not win]
    - "\"%R%\" -e \"library('rversions')\""  # [win]

about:
  home: https://github.com/metacran/rversions
  license: MIT
  summary: Query the main 'R' 'SVN' repository to find the versions 'r-release' and 'r-oldrel'
    refer to, and also all previous 'R' versions and their release dates.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
