travis:
  secure:
    BINSTAR_TOKEN: aZzerxec3/dr4Wv9mAvW7xUeQBdF4kCSRwMEoGsSOgrGf/dvAq5YjVkz50bBXSDnJ7OYELF/rvE+Ax4/zqavsWMItjO1esn/yBaSzfY3ahGvpJvhz8cz+YaPaaVSGDiUjhoGptUDqyDXchTP46YLXd3JQGC23D+W8+Ke1JQt1HP/dHOPLlbhMhV9GpcItCt1xBsZy33+tswLvgz4YyopuMN3sO3yvtB7FDfsvaOsJl3KFEq6ZHkTPgzBb7cCkeYrNPn3iLA6td/VLcGuZNy8ceFkY5J+EJ/hhvfsSIjUfJZRomQmaTZIOZKwTui+IED8tFKJKSCPylEfl4q+lbjznfF6TB0RnCbm8TBfPtjl8m7T6xeo3gIwcn8kS2s0G2/z2qP4dG3cmPxEMm8SbcWvfYnVjMYz13Nv5UZCphTl9VaoroCwYo/rxOstOEDEtI+Soh+kDRDoc6WUAovSQQIY6LQKqgv6XXyMicCx5QHtQ4R2zgU0O1NmI2hHjTSOAjE6vz6xu1zraw5IvzbjG9QSdUg0Jzl9V59hMJL1aG0oPfg1WJ5HgC/PifHgsV4+C7lXqLhMM2Yp6UOEXDG+JhYXtE/yAClUwDFBhK83T3rmDD8VBPnIB1SadmJycATRh6N2YO0+WrrtwEKFGrOOsxGF3128okX6l10bFPsT7UYl4Mg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
